universe = vanilla
executable = $(condor_dir)/run_data.sh
arguments = $(events) $(skip_events) $(input_file) $(output_file)
environment = "DMR_CMSSW_BASE=$(cmssw_base)"

use_x509userproxy = True
x509userproxy = $(proxy)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = $(output_file)
output_destination = $(output_destination:)
transfer_output_remaps = "$(output_remaps:)"
MY.XRDCP_CREATE_DIR = True

request_cpus = 1
request_memory = 2000MB
request_disk = 2GB
+JobFlavour = "workday"

output = $(log_root)/job_$(ClusterId)_$(ProcId).out
error = $(log_root)/job_$(ClusterId)_$(ProcId).err
log = $(log_root)/cluster_$(ClusterId).log

queue events,skip_events,input_file,output_file from $(job_list)
